export const EVENT_KEYS = {
  CONNECT: 'connect',
  CONNECTED: 'connected',
  DISCONNECTED: 'disconnected',
  ERROR: 'error',
  CONNECT_ERROR: 'connect_error',
  PUB_UPDATE_STATUS: 'updateStatus',
  SUB_UPDATE_STATUS: 'userStatusChanged',
  PUB_START_TYPING: 'startTyping',
  SUB_START_TYPING: 'userStartTyping',
  PUB_STOP_TYPING: 'stopTyping',
  SUB_STOP_TYPING: 'userStopTyping',
  PUB_JOIN_WORKSPACE: 'joinWorkspace',
  SUB_JOIN_WORKSPACE: 'workspaceJoined',
  SUB_NOTICE_WORKSPACE: 'workspaceNotice',
  PUB_CHANGE_WORKSPACE: 'changeWorkspace',
  PUB_LEAVE_WORKSPACE: 'leaveWorkspace',
  PUB_JOIN_CHANNEL: 'joinRoom',
  PUB_JOIN_ROOM: 'joinRoom',
  PUB_LEAVE_CHANNEL: 'leaveChannel',
  PUB_SEND_MESSAGE: 'sendMessage',
  SUB_CHANNEL_CREATED: 'channelCreated',
  SUB_CHANNEL_UPDATED: 'channelUpdated',
  SUB_CHANNEL_DELETED: 'channelDeleted',
  SUB_CHANNEL_LEAVED: 'channelLeaved',
  SUB_DM_ROOM_CREATED: 'dmRoomCreated',
  SUB_NEW_MESSAGE: 'newMessage',
};
