import type { Metadata } from 'next';
import './globals.css';
import { purpleTheme } from '@/shared/styles/theme.css';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={purpleTheme}>{children}</body>
    </html>
  );
}
